# Generated by Django 4.1.6 on 2023-02-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whois_app', '0002_searchterm_user_location_alter_searchterm_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
